version: '3'
services:
  api:
    build: .
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 12345.
      DB_NAME: prueba_fhios
      PORT: 3000
      SECRET_KEY: mysecretkey
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 12345.
      MYSQL_DATABASE: prueba_fhios
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
